/* test_video.c — headless tests for the video editor core (R008/R009/R016).
 *
 * Verifies Tier 0 (track-kind constants) and Tier 1a (lossless keyframe trim +
 * ffmpeg-filter segment detection). Uses a synthetic test clip at
 * /tmp/vidtest/src.mp4 (generated by the Makefile / CI).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "wbus/wbus_video.h"
#include "wbus/wbus.h"

static int failures = 0;
static int checks = 0;
#define CHECK(cond, msg) do { \
    checks++; \
    if (cond) printf("  [PASS] %s\n", msg); \
    else { printf("  [FAIL] %s\n", msg); failures++; } \
} while (0)

/* Generate a tiny test clip via ffmpeg if missing. */
static void ensure_test_clip(const char *path) {
    /* If present, skip. */
    FILE *f = fopen(path, "rb");
    if (f) { fclose(f); return; }
    const char *ff = FFmpeg_BIN;
    char cmd[1024];
    snprintf(cmd, sizeof(cmd),
             "\"%s\" -y -f lavfi -i \"testsrc=size=320x240:rate=25:duration=4\" "
             "-f lavfi -i \"sine=frequency=440:duration=4\" "
             "-c:v mpeg4 -c:a aac -shortest \"%s\" > /dev/null 2>&1",
             ff, path);
    system(cmd);
}

int main(void) {
    printf("=== Video editor core test (Tier 0 + 1a) ===\n\n");

    /* ---- Tier 0: track-kind constants do not collide ---- */
    CHECK(WB_TRACK_KIND_INSTR == 0, "INSTR kind == 0");
    CHECK(WB_TRACK_KIND_AUDIO == 1, "AUDIO kind == 1");
    CHECK(WB_TRACK_KIND_BUS   == 2, "BUS kind == 2");
    CHECK(WB_TRACK_KIND_VIDEO == 3, "VIDEO kind == 3 (distinct from BUS)");
    CHECK(WB_TRACK_KIND_VIDEO != WB_TRACK_KIND_BUS, "video != bus (no collision)");

    /* Generate a changing clip too (for scene detection, which needs cuts). */
    const char *chg = "/tmp/vidtest/changing.mp4";
    {
        FILE *f = fopen(chg, "rb");
        if (!f) {
            char cmd[1024];
            snprintf(cmd, sizeof(cmd),
                     "\"%s\" -y -f lavfi -i \"testsrc=size=320x240:rate=25:duration=2\" "
                     "-f lavfi -i \"testsrc2=size=320x240:rate=25:duration=2\" "
                     "-filter_complex \"[0][1]concat=n=2[v]\" -map \"[v]\" -c:v mpeg4 \"%s\" >/dev/null 2>&1",
                     FFmpeg_BIN, chg);
            system(cmd);
        } else fclose(f);
    }

    const char *src = "/tmp/vidtest/src.mp4";
    ensure_test_clip(src);

    /* ---- Decoder sanity (existing API) ---- */
    wb_video_decoder *d = wb_video_decoder_open(src);
    CHECK(d != NULL, "decoder opened test clip");
    if (d) {
        double dur = wb_video_decoder_get_duration(d);
        CHECK(dur > 3.5 && dur < 4.5, "source duration ~4s");
        wb_video_decoder_close(d);
    }

    /* ---- Tier 1a: lossless keyframe trim (concat demuxer + -c copy) ---- */
    wb_video_segment segs[2] = {
        { 0.5, 1.5 },   /* keep 1.0s */
        { 2.5, 3.5 },   /* keep 1.0s */
    };
    const char *out = "/tmp/vidtest/trimmed.mp4";
    remove(out);
    int rc = wb_video_lossless_trim(src, segs, 2, out);
    CHECK(rc == 0, "lossless trim returned 0");
    FILE *f = fopen(out, "rb");
    CHECK(f != NULL, "trimmed output file exists");
    if (f) {
        fclose(f);
        /* Verify the trimmed file is ~2.0s by re-opening with our decoder. */
        wb_video_decoder *dt = wb_video_decoder_open(out);
        CHECK(dt != NULL, "trimmed file re-decodable");
        if (dt) {
            double td = wb_video_decoder_get_duration(dt);
            printf("         trimmed duration ~%.2fs\n", td);
            CHECK(td > 1.5 && td < 2.5, "trimmed duration ~2.0s");
            wb_video_decoder_close(dt);
        }
    }

    /* ---- Tier 1a: scene-change detection (pure ffmpeg) ---- */
    wb_video_segment det[64];
    int nseg = wb_video_detect_segments(chg, 0, 0.1, det, 64);
    CHECK(nseg >= 0, "scene detect ran without error");
    CHECK(nseg > 0, "scene detect found change points");
    if (nseg > 0) {
        printf("         detected %d scene points; first @ %.2fs\n", nseg, det[0].start);
        CHECK(det[0].start >= 0.0, "first scene point time valid");
    }

    /* ---- Tier 1a: silence detection ---- */
    int nsi = wb_video_detect_segments(src, 2, 0.5, det, 64);
    CHECK(nsi >= 0, "silence detect ran without error");
    printf("         silence segments: %d\n", nsi);

    /* ---- Tier 0b: session video clip lifecycle (the half-wired API) ---- */
    {
        wb_session *s = wb_session_create();
        CHECK(s != NULL, "session created for video clip test");

        int vt = wb_session_add_video_track(s, "V1");
        CHECK(vt >= 0, "video track added");
        CHECK(s->tracks[vt].kind == WB_TRACK_KIND_VIDEO, "track kind is VIDEO");

        int ci = wb_session_add_video_clip(s, vt, src, 0.0);
        CHECK(ci >= 0, "video clip added to session");
        CHECK(s->tracks[vt].clips[ci].video != NULL, "clip carries video struct");

        /* duration must be resolved (was left 0 before the fix) */
        double dur = s->tracks[vt].clips[ci].video->duration;
        CHECK(dur > 3.5 && dur < 4.5, "clip duration resolved from source (~4s)");
        CHECK(s->tracks[vt].clips[ci].length > 3.5, "clip length set from duration");

        /* hit-testing: a time inside the clip must find it (was broken at >0s) */
        int hit0 = wb_session_video_clip_at(s, vt, 0.0);
        int hit1 = wb_session_video_clip_at(s, vt, 2.0);   /* mid-clip */
        int hitX = wb_session_video_clip_at(s, vt, 10.0);  /* past end */
        CHECK(hit0 == ci, "hit-test at t=0 finds clip");
        CHECK(hit1 == ci, "hit-test at t=2s finds clip");
        CHECK(hitX < 0, "hit-test past end finds nothing");

        /* remove: must free the struct and compact the array */
        int rc = wb_session_remove_video_clip(s, vt, ci);
        CHECK(rc == 0, "remove video clip returned 0");
        CHECK(s->tracks[vt].clip_count == 0, "track clip_count back to 0 after remove");
        CHECK(s->tracks[vt].clips == NULL, "clip array freed after remove");

        wb_session_destroy(s);
    }

    printf("\n%d checks, %d failures\n", checks, failures);
    return failures == 0 ? 0 : 1;
}
